client/session.go
memspool/server/cmd/memspool/main.go
panda/server/cmd/panda_server/main.go
ping/main.go
ping/ping.go
reunion/servers/reunion_katzenpost_server/main.go
server/internal/provider/kaetzchen/cbor_plugins.go
server/internal/provider/kaetzchen/kaetzchen.go
server_plugins/cbor_plugins/echo-go/main.go

this isn't ready to be merged yet

Unfuck length prefixing

---

ping/ping.go
server_plugins/cbor_plugins/echo-go/main.go

herein lies simple and obvious fixes

Fix ping and cbor echo service plugin

---

core/sphinx/commands/commands_vectors_test.go
core/sphinx/sphinx_vectors_test.go
core/wire/commands/commands_vectors_test.go
reunion/client/exchange.go
reunion/client/state.go
reunion/crypto/elligator.go
reunion/crypto/session.go
reunion/server/state.go

Where possible I replaced the cbor encoder that we were using, as per:
https://github.com/katzenpost/core/issues/103

Replace cbor encoder

---

minclient/connection.go

This PR is created to track proposed fixes to minclient that remove deadlock on the connection Lock

minclient: fix deadlock onConnStatusChange and getConsensus

---

panda/client/client.go

if BlockingSendReliableMessage returns an error, for example if the outbound message queue is full, then instead of looping as fast as possible goto Sleep and try again later.

fix panda client.Exchange spinning on error sending

---

docs/drafts/client.rst
docs/drafts/deaddrop.rst
docs/drafts/decoy_traffic.rst
docs/drafts/keyserver.rst
docs/drafts/noname_messaging.txt
docs/drafts/panda.txt
docs/drafts/zcash_send.rst
docs/papers/catshadow_threat_model/bibliography.bib
docs/specs/kaetzchen.rst
docs/specs/lioness.rst
docs/specs/mixnet.rst
docs/specs/old/end_to_end.rst
docs/specs/pki.rst
docs/specs/sphinx_replay_detection.rst

Fixed urls in docs

---

server/internal/decoy/decoy.go

Fix bug described here: https://github.com/katzenpost/katzenpost/issues/98

Fix mix crash bug

---

authority/internal/s11n/descriptor.go
authority/internal/s11n/document.go

Fix bug describe in this ticket here https://github.com/katzenpost/katzenpost/issues/103

Fix voting auth cert db bug

---

sphincsplus/ref/binding.go

Make sphincsplus cgo bindings be compatible on all platforms

---

server/internal/decoy/decoy.go

fixes https://github.com/katzenpost/katzenpost/issues/133

mixserver/decoy: don't panic on AVL tree bug

---

.github/workflows/go.yml

If we merge this tiny change to our github workflow... it gives us code coverage reports automatically... which seems nice to me. So let's try it?

Add codecov to github ci workflow

---

client/session.go
memspool/client/client_docker_test.go

fix for..range variable reuse bug

fixes a for..range bug in client.Session.GetServices 

---

docker/Makefile
genconfig/main.go
memspool/client/client_docker_test.go
server/internal/decoy/decoy.go

this bug prevents decoy traffic from working properly as the mix will crash.

Fix decoy traffic

---

server/internal/decoy/decoy.go

fix some of the server decoy traffic bugs

Attempt to fix server decoy

---

server/internal/pki/pki.go

adjust the pki wakeup timer so that it sleeps until the pki publication deadline

server: pkiclient refetch according to voting scheule

---

catshadow/client.go

rather than panic, return an error
https://github.com/katzenpost/katzenpost/issues/164

Fix panic on addcontact without spool

---

go.mod
go.sum

use v0.0.15 with the fix for #116

---

catshadow/client.go

To be rebased on `main` after merging https://github.com/katzenpost/katzenpost/pull/223
- This makes sure we don't leave `LastMessage = nil` when there are live messages still in the conversation
- and memoizes the `time.Now()` arithmetic to slightly speed up things

Catshadow.garbage collect conversations

---

catshadow/client.go

This simple PR adds a catshadow client method that helps out with the upgrade

catshadow: add client method DoubleRatchetPayloadLength

---

server/internal/instrument/prometheus.go
server/internal/instrument/prometheus_dummy.go
server/internal/outgoing/connector.go
server/internal/outgoing/outgoing_conn.go
server/internal/scheduler/queue_bolt.go

#318  Adds packet drop counters for different types of packet drop events

318 improve prometheus metrics

---

core/crypto/cert/cert_test.go

```
--- PASS: TestWrongCertificate (0.92s)
=== NAME  TestBadCertificate
cert_test.go:87:
Error Trace:
/home/runner/work/katzenpost/katzenpost/core/crypto/cert/cert_test.go:87
Error:       An error is expected but got nil.
Test:        TestBadCertificate
--- FAIL: TestBadCertificate (0.61s)
```
This happens when `certificate[1000] == 235` in which case no modification is made, and we unexpectedly get an OK from `Verify()`. This used to happen in 1/256 test executions.
Also bumps the expiry by one so we're not impacted by epoch rollover between `Sign()` and `Verify()`, which we haven't run into, but could happen one day.

Fix transient errors in TestBadCertificate:

---

authority/voting/server/state.go
authority/voting/server/state_test.go

Draft status because we don't know if this starts panic()ing all over the place.
Hopefully CI can make us wiser.

authority/voting/server: replace lock comments by lock assertions

---

README.md

this should be re-added when a top-level Makefile is added so that this actually works, but until then it is confusing to have this here.

remove inaccurate section from readme 

---

core/crypto/nike/hybrid/no_nobs_csidh.go

fixes https://github.com/katzenpost/katzenpost/issues/386

core/crypto/nike/hybrid: fix broken ppc64le build

---

bench/bench_test.go

this fixes bench test, if the parametized network uses a different geometry

bench/bench_test: use SphinxGeometry from client configuration

---

docker/Makefile
genconfig/main.go

This PR exposes log_level to the dockerized mixnet deployment.

Add loglevel to genconfig

---

authority/voting/client/client.go
authority/voting/server/state.go

authority: log the consensus produced at NOTICE loglevel

---

authority/voting/server/state.go

Authorities can learn about MixDescriptors from other Authorities

omit hasEnoughDescriptors

---

authority/voting/client/client.go

authority/client: fix off by one

---

docs/getting-started/kips.md

Rough pass at a proposed flow for writing specifications for code submissions to project!

Add docs kips

---

.github/workflows/go.yml
go.mod
go.sum

if all tests pass then please merge me

Use latest highctidh

---

docs/handbook/mix_server.md

Update section referring to CBOR plugin, remove incorrect information regarding CBOR-over-HTTP and mention limitations of the client plugin.

docs/handbook/mix_server.rst: update CBORPlugin section

---

server/internal/gateway/gateway.go
server/internal/instrument/prometheus.go
server/internal/instrument/prometheus_dummy.go
server/internal/scheduler/scheduler.go
server/internal/service/kaetzchen/kaetzchen.go
server/internal/service/service.go
server/server.go

Resolves https://github.com/katzenpost/katzenpost/issues/574

add prometheus Gauge Channel Length

---

tools/mixnet-params.py

This PR:
* adds a click cli (run with --help for usage)
* moves all of the parameters to globals to make it easier to read
* prints parameters and genconfig arguments
* reformats all of the code with the "black" Python code formatting tool
* produces the same results as the script did prior to these changes

cleanup mixnet-params.py

---

genconfig/main.go

Resolves https://github.com/0KnowledgeNetwork/devops/issues/76

genconfig nodecoy param

---

client2/client_docker_test.go
client2/listener.go

Resolves https://github.com/katzenpost/katzenpost/issues/683

fix client2 test address already in use panic

---

catshadow/client_docker_test.go
client/client_docker_test.go

there are other bugs like this too

client/client_docker_test: do not use testify from multiple goroutines

---

client2/config/config.go
client2/connection.go
core/pki/descriptor.go
core/pki/document.go
genconfig/main.go
server/internal/incoming/listener.go
server/internal/pki/pki.go

this makes it possible to announce a .onion

server, pki: fix handling of .onion Address lines

---

core/pki/descriptor.go
genconfig/main.go

remove the IP version check that breaks IPv6 address parsing

remove expectedIPVer check

---

.github/workflows/docker-mixnet.yml
.github/workflows/release.yml
docker/Makefile
genconfig/main.go

This reverts commit 948e15c6fe1f064f5c77dd36feb0e02a94265474.

Revert "remove broken release workflow"

---

docs/client_integration.md

Rewriting and adding building instutions

editing client integration guide

---

ping/main.go

This reverts commit 4f402e10955a1a2162f795c86119bd75c54a19e3.

Revert "Fixup ping to not start client2 daemon by default"

---

pigeonhole/pki.go
pigeonhole/pki_test.go

Fixup GetRandomIntermediateReplicas

Fixup thinclient bugs

---

authority/voting/server/wire_handler.go
core/wire/session.go

- authority/voting/server: increase handshake timeout from 30s to 90s
- authority/voting/server: increase connection close delay from 100ms to 1000ms
- authority/voting/server: add handshake timing and auth success logging
- core/wire: add 30s read timeouts to prevent indefinite hangs
Fixes 'failed to receive NoOp command from peer' errors on slower network paths between directory authority nodes.

authority/wire: fix handshake timeouts and connection delays

---

authority/voting/client/client.go
authority/voting/server/state.go

- Remove premature authorization check from descriptor upload
- Change voting client to use threshold-based success (majority vs all)
- Fix hasEnoughDescriptors variable reference bug (nrNodes -> nrMixNodes)
Restores proper separation: uploads accept all descriptors, authorization filtering happens during vote tallying phase.

Fix descriptor upload and consensus validation issues
