katzenpost/katzenpost

- authority/internal/s11n/descriptor_test.go
- authority/internal/s11n/document.go
Fixes an issue where signatures may not agree due to differences in expiration time.
This should be validated with integration tests before merging
> Make SignDocument use certificate expirate derived from epoch base

- catshadow/client.go
- client/session.go
- minclient/connection.go
In each case, a channel read or write is wrapped in a select along with the halt channel so that it can halt; for the catshadow API methods, a requested shutdown would block API methods from returning.
> This PR fixes a few more blocking channel operations in minclient and catshadow

- authority/internal/s11n/descriptor.go
- authority/internal/s11n/document.go
The next epoch the descriptor becomes valid, and contains 3 epochs worth of MixKeys, so it should be valid for current epoch + 4
See #83
> Extend MixDescriptor certificate expiration to 3 epochs

- core/wire/noise_test.go
- docs/specs/wire-protocol.rst
update the wire protocol spec so it accurately represents what we are now using. 
fixes this ticket: https://github.com/katzenpost/katzenpost/issues/108
> Update noise wire protocol spec

- docs/specs/mixnet.rst
recent changes to our sphinx format makes the security parameter 256 bits except for the SPRP which we need to upgrade later
> Corrections to Sphinx params

- server/internal/decoy/decoy.go
This PR fixes first crash bug from issue https://github.com/katzenpost/katzenpost/issues/133
It is a workaround style bug fix where we know for sure (because of gaurantees of golang type system) that the bug is in the AVL library. See ticket to replace with priority queue here: https://github.com/katzenpost/katzenpost/issues/134
> fix for half of #133

- catshadow/client.go
- catshadow/client_docker_test.go
- catshadow/client_test.go
- catshadow/operations.go
- catshadow/worker.go
- client/session.go
This branch adds additional methods to catshadow so that a user of catshadow can create spools on a named provider.
> Add CreateRemoteSpoolOn(provider), GetPKIDocument(), GetSpoolProviders(), SpoolWriteDescriptor()  to catshadow

- docker/Makefile
- server/Makefile
Add flags to minimize differences in binary output of go build for use in reproducibly building daemons.
> builds: add flags -trimpath and -ldflags -buildid=

- core/wire/kem.go
This fixes a stupid cryptography bug where i was calling generate key in each key unmarshal. But it turns out we don't have to do that because the upstream library, nyquist provides the parse methods. so it was my fault all along. sorry about that.
> core/wire: fix KEM key unmarshaling

- .github/workflows/go.yml
this should cause our github ci workflow to generate code coverage reports which our codecov will render into a report
> Fix codecov coverage reports

- authority/voting/client/client.go
- docker/Makefile
this PR changes the pki client (authority/voting/client) Get() behavior so that if an authority tells the client that there will never be a document for the current epoch the client will retry and ask other authorities up to threshold (number of authorities / 2) times before returning ErrNoDocument.
this fixes #180
> Pki retry threshold

- catshadow/client.go
when renaming a contact before any messages were received, the copying of the conversations was setting the conversations[nickname] map to nil
https://github.com/katzenpost/katzen/issues/21
> catshadow: make client check for nil map

- core/crypto/eddsa/blinded25519.go
- core/crypto/eddsa/blinded25519_test.go
This implements the missing `BlindedPrivateKey.Blind` operation so you can use the commutative properties of the Blind operation.
Refactored `func (k *PrivateKey) Blind(` to share code with the new `func (k *BlindedPrivateKey) Blind(`
> Blinded25519: Commutative BlindedPrivateKey.Blind()

- .github/workflows/go.yml
This reverts commit ee3c5bcfe82ce393dd969698c2c034427e6e3ed1.
This brings back CI to PRs so they can be merged.
> Revert "stop running ci twice"

- catshadow/client.go
- client/client.go
- client/client_docker_test.go
- client/session.go
- memspool/client/client_docker_test.go
- minclient/client.go
- minclient/connection.go
- minclient/pki.go
- panda/client/client.go
- panda/crypto/panda.go
- ping/main.go
This PR changes the client API slightly so that the caller can cancel a session rather than using a baked-in timeout of 45s
> client: make NewTOFUSession and PKIBootstrap require context.Context

- server/cborplugin/server.go
this fixes a deadlock issue reported in #263
> server: cborplugin worker must always write a response

- docker/Makefile
The current default docker decoy traffic setting is so aggressive that my laptop freezes up for a few seconds at a time while I'm trying to type into my text editor and I am very frustrated. Let's merge this.
> docker: Less aggressive default decoy traffic

- authority/voting/server/state.go
see #302 and #305 
We weren't returning the `err` so we got the nondescript catch-all error in this case.
> tallyVotes: return err when decoding bs (params) fails

- authority/voting/server/state.go
#320 do not exit loop until checking all parameter choices
I suspect this might account for an off-by-one err if the tallying node is the tie-breaker
> authority: skip dissenting parameter votes

- server/cborplugin/client.go
- server/cborplugin/socket.go
- server/internal/provider/kaetzchen/cbor_plugins.go
This PR handles a kaetzchen plugin crash gracefully by unregistering it from the set of services.
> Fix 323 handle cborplugin failure

- docker/Makefile
this is useful for creating a testnet with an old version and then upgrading it without deleting the network state (as `clean-local` does).
> docker/Makefile: add clean-bin target

- authority/voting/client/client.go
this fixes a nil ptr panic when every connection fails and conn is nil
> authority/client/connector: return on error, simplify conn.Close logic

- server/config/config.go
- server/config/config_test.go
- server/internal/instrument/prometheus.go
- server/internal/instrument/prometheus_dummy.go
- server/internal/pki/pki.go
- server/internal/provider/kaetzchen/kaetzchen.go
- server/server.go
Adds MetricsAddress to the mix server config so that the operator can configure a metrics listener that will work with the prometheus collector, or disable prometheus entirely.
fixes https://github.com/katzenpost/katzenpost/issues/363 , builds on https://github.com/katzenpost/katzenpost/pull/390
> add configurable metrics endpoint address

- core/crypto/cert/cert_test.go
this fixes a bug where tests occasionally fail due to a certificate expiration, presumably at an epoch bound
> core/crypto/cert: Sign current+2 so tests do not fail across epochs

- docker/Makefile
- genconfig/main.go
this adds bind_addr environment variable that will configure the listening address for the mix and authority nodes. you can use this to make a testnet reachable via the public internet for testing or demonstration purposes.
> genconfig, docker: make listening address configurable

- docker/Makefile
I noticed that docker-compose stopped working when upgrading from alpine 3.17 to alpine 3.18. (docker-cli-compose 2.15.1-r3 -> 2.17.3-r6)
> docker: fix DOCKER_HOST env as newer versions of docker-compose needs a URL

- authority/voting/server/state.go
the voting authority config now holds all the authorities, including itself. this stops the authority from sending commands to itself.
fixes #407, #316
> authority: do not send commands to self

- server/internal/pki/pki.go
if there are enough bootstrapping/failed authorities and no consensus is found before the MixDescriptor publish deadline, the mix server may not publish a descriptor in time.
> server/internal/pki: publish descriptor first, before fetching consensus

- Makefile
- sphincsplus/ref/binding.go
- sphincsplus/ref/params.h
- sphincsplus/ref/raft/PQCgenKAT_sign.c
- sphincsplus/ref/raft/rng.c
- sphincsplus/ref/randombytes.c
- sphincsplus/ref/randombytes.h
- sphincsplus/ref/rng.h
- sphincsplus/ref/sign.c
- sphincsplus/ref/test/benchmark.c
- sphincsplus/ref/test/fors.c
- sphincsplus/ref/test/haraka.c
- sphincsplus/ref/test/spx.c
This change removes the need to set `CGO_CFLAGS_ALLOW` before building sphincsplus, and it adds a `Makefile` target called `sphincsplus` to run relevant tests:
$ make sphincsplus
cd sphincsplus/ref && go test -v -race -timeout 0 ./...
=== RUN   TestSignVerify
=== PAUSE TestSignVerify
=== RUN   TestSerialization
=== PAUSE TestSerialization
=== RUN   TestSizes
=== PAUSE TestSizes
=== RUN   TestSignVerifyVector
--- PASS: TestSignVerifyVector (0.06s)
=== CONT  TestSignVerify
=== CONT  TestSizes
=== CONT  TestSerialization
=== CONT  TestSizes
binding_test.go:62: PrivateKeySize 128
binding_test.go:63: PublicKeySize 64
binding_test.go:64: SignatureSize 49856
--- PASS: TestSizes (2.27s)
--- PASS: TestSerialization (4.68s)
--- PASS: TestSignVerify (6.91s)
PASS
ok …
> Remove the need for setting CGO_CFLAGS_ALLOW

- core/crypto/nike/ctidh/ctidh.go
- core/crypto/nike/ctidh/ctidh_test.go
- core/crypto/nike/hybrid/ctidh.go
- core/crypto/nike/schemes/schemes.go
- go.mod
- go.sum
- sphincsplus/ref/randombytes.h
This uses a new highctih golang module that replaces the use of `ctidh_cgo` which previously required a system library. The new highctidh golang modules do not require a system library and behave as a normal golang module.
$ go test -v
=== RUN   TestCtidhNike
--- PASS: TestCtidhNike (8.41s)
PASS
ok  	github.com/katzenpost/katzenpost/core/crypto/nike/ctidh	8.426s
> use highctidh.ctidh1024 golang module

- core/crypto/nike/ctidh1024/ctidh.go
- core/crypto/nike/ctidh1024/ctidh_test.go
- core/crypto/nike/ctidh2048/ctidh.go
- core/crypto/nike/ctidh2048/ctidh_test.go
- core/crypto/nike/ctidh511/ctidh.go
- core/crypto/nike/ctidh511/ctidh_test.go
- core/crypto/nike/ctidh512/ctidh.go
- core/crypto/nike/ctidh512/ctidh_test.go
- core/sphinx/ctidh1024_benchmark_test.go
- core/sphinx/ctidh2048_benchmark_test.go
- core/sphinx/ctidh511_benchmark_test.go
- core/sphinx/ctidh512_benchmark_test.go
- core/sphinx/kemsphinx_test.go
- core/sphinx/sphinx_ctidh1024_test.go
- core/sphinx/sphinx_ctidh2048_test.go
- core/sphinx/sphinx_ctidh511_test.go
- core/sphinx/sphinx_ctidh512_test.go
- core/sphinx/sphinx_test.go
This change makes sure that the Sphinx unit tests are testing for the correct packet size at each stop in the packet unwarp. Here we also add a SURB test for KEM Sphinx. And we fix the CTIDH Sphinx tests.
> sphinx: improve tests

- docker/Makefile
i broke this 13 months ago... the shell target should be able to get online. it was not because of a stray -e argument (to set environment) which consumed the --network=host argument.
this also removes the --network=host (and stray -e) from the ping build command, since it doesn't need network at all.
> fix testnet shell

- server/internal/mixkey/mixkey.go
- server/internal/mixkey/mixkey_test.go
- server/mixkey.go
This eliminates problematic MixKey persiistence to disk. Previously, the mix server would write key material to disk, and not erase it until the mix service was restarted.
Instead, mix servers should do graceful upgrades by halting the mix at end of epoch and restarting into a new epoch with new in-memory key material.
> server/internal/mixkey: eliminate mixkey perisistence

- authority/voting/server/wire_handler.go
If there is no document available for the requested epoch, the requesting client IP is being logged.
> authority/voting/server: omit logging PII upon GetConsensus failure

- authority/voting/server/config/config.go
Merging this PR will fix a bug in the dirauth server thus allowing it to generate new keys with the -g flag.
> Fix -g flag to dirauth server

- go.mod
- go.sum
recently merged some upstream changes into nyquist fork. additions to hpqc. this pr makes katzenpost monorepo use the latest.
> Use latest nyquist and hpqc

- authority/Makefile
- bench/Makefile
- catshadow/Makefile
- client/Makefile
- docker/Makefile
- memspool/Makefile
- minclient/pki.go
- server/Makefile
- server/internal/pki/pki.go
we used to need to set and check WarpedEpoch in more places but now it is only used in core/epochtime/time.go so we only need to set it there.
fixes https://github.com/katzenpost/katzenpost/issues/562
> remove some WarpedEpoch-related cruft

- authority/voting/client/client_test.go
- authority/voting/server/state_test.go
- client/config/config.go
- core/pki/descriptor.go
- core/pki/descriptor_test.go
- core/pki/document.go
- core/pki/document_test.go
- minclient/client.go
- server/config/config.go
- server/internal/decoy/decoy_test.go
- server/internal/pki/pki.go
The goal is to get rid of the golang type alias within core/pki. The pki Transport type alias is really just a string however using this type alias complicates a lot of client code. Changing this back to string will be a welcome change.
> core/pki: get rid of Transport type alias

- panda/crypto/panda_test.go
This PR resolves the deadlock issue in https://github.com/katzenpost/katzenpost/actions/runs/9216037360/job/25356619537?pr=588
```
panic: test timed out after 30m0s
running tests:
TestKeyExchangeWithSerialization (30m0s)
```
The error is probably happening because no other part of the application is producing data to  `pandaChan`, due to a tight loop, adding select/default makes it non-blocking.
> fix TestKeyExchangeWithSerialization

- server/internal/gateway/gateway.go
- server/internal/instrument/prometheus.go
- server/internal/scheduler/scheduler.go
- server/internal/service/kaetzchen/kaetzchen.go
- server/internal/service/service.go
- server/server.go
The extra goroutines used for the Prometheus gauges of buffered channel usage are causing high mix server load.
> BUG FIX: Remove prometheus goroutines for monitoring buf chans

- doubleratchet/ratchet_test.go
- go.mod
- go.sum
This changes the doubleratchet test's nike to NOBS_CSIDH512X25519, and upgrades to the latest hpqc with https://github.com/katzenpost/hpqc/pull/30 which fixes the bug which made doubleratchet unable to use it.
> ratchet_test.go: use NOBS_CSIDH512X25519

- catshadow/client_docker_test.go
- client2/Makefile
- client2/client.go
- client2/client_docker_test.go
- client2/connection.go
- client2/daemon.go
- client2/listener.go
- client2/sender.go
- client2/thin/thin.go
- docker/Makefile
This PR resolves #673 and fixes some bugs in client2 shutdown path
- **DEBUG: add pprof http listener**
- **client2.NewListener: return err from net.ListenTCP**
- **call EventSink() before SendMessage**
- **client2: client_docker_test: shutdown cleanly on os.Interrupt**
- **client2/client_docker_test: do not listen on prometheus default listening port**
- **client2/Makefile: do not run go test in subshell**
- **do not remotely resolve missing images**
- **client2/Makefile: ensure target image exists**
- **client2/Makefile: allocate tty to pass sigint to container**
- **Revert "DEBUG: add pprof http listener"**
> fix 673 sigint

- client2/client.go
- client2/client_docker_test.go
- client2/connection.go
- client2/daemon.go
- client2/exponential.go
- client2/incoming_conn.go
- client2/listener.go
- client2/pki.go
- client2/thin/thin.go
- client2/timer_queue.go
- genconfig/main.go
this collection of commits fixes issues found while debugging the client2 dockerdockertest make target.
in particular there were several issues with blocked routines at shutdown, a missing "+" required for addressing kaetzchen endpoints, misbehaving fetchInterval loop and aggressive garbage collection timeout resulted in SURB Replies being dropped.
- **Reapply "DEBUG: add pprof http listener"**
- **add -noMixDecoy to genconfig**
- **genconfig: disable client2 decoy traffic with -noDecoy**
- **client2: fix testtest endpoint**
- **client2: connection: run peer reader with worker.Go**
- **client2: listener: eliminate redundant Wait()**
- **client2: Shutdown conn and pki worker before halting client worker**
- **client2: incoming_conn, connection: start workers with worker.Go()**
- …
> fix client2 dockerdockertest

- client/client.go
when client is Shutdown gracefully, the fatalErrCh should not WARN
> client: fatalErr watcher should not WARN at close of fatalErrCh

- authority/voting/server/server.go
- core/pki/descriptor.go
- core/pki/document.go
- genconfig/main.go
- http/common/quic.go
- http/proxy/client/main.go
- server/internal/incoming/listener.go
- server/internal/pki/pki.go
* Rename internally used transport endpoint; call it "quic" instead of "http".
* Remove quic listener code duplication from authority/voting/server/server.go
* Make genconfig default to using TCP instead of QUIC
> Change transport endpoint to "quic"

- stream/buffered.go
if result is not drained, then worker blocks and does not shut down.
making result buffered also allows returning an error if result was not obtained at shutdown.
> stream: make BufferedStream.CBORDecodeAsync not block if result is not drained

- docs/Admin_guide/source/en/docker.xml
remove redundant command
remove old "run" target, and document "wait"
> docs: improve docker instructions

- authority/voting/server/state.go
- authority/voting/server/state_test.go
- client2/incoming_conn.go
- client2/listener.go
- client2/pki.go
- client2/thin/thin.go
- core/pki/document.go
- core/pki/document_test.go
- genconfig/main.go
* The goal here is to serialize the pki Document with CBOR and send that to Thin Client apps with the signatures removed to save bandwidth because the client daemon has checked the signatures already. This turned out to be very difficult.
* The other main goal is to fix the thin client protocol so that it always uses the length prefixing whereas previously it only used length prefixing for tcp.
One of the reasons it's problematic to have the methods for binary marshaler/unmarshaler on the pki Document type is because our actual implementation is a complete lie and does not actually unmarshal the PKI Document type and instead unmarshals the Certificate struct type which contains public keys and signatures.
The other reason it's problematic is because it prevents use from using the cbor …
> Fixup client2 thin client protocol

- client2/pki.go
- client2/thin/thin.go
Minor improvements to the client2 thin client's select statements such that it selects on additional events that it previously was not so that it responds to context done and halting events.
Make some correction to client2 logging. Reduce the superfluous verbosity. Correction.
> client2/thin: fixup client2

- bench/bench_test.go
- core/cert/cert.go
- genconfig/main.go
Here we fix a signing bug that prevented us from using some of the signature schemes made available in hpqc, namely it lets us use the Signature schemes from our fork `circl` library if we've specifically made them available.
> Fix Signing bug + genconfig: default to dilithium

- .github/workflows/docker-mixnet.yml
- docker/Makefile
This makes it possible to pass `no_decoy=false no_mixdecoy=false` to `make` to enable cover traffic in the containerized testnet.
> docker/Makefile: fix no_decoy and no_mixdecoy options

- client2/exponential_test.go
- client2/timer_queue_test.go
prevent client2's time related unit tests from running by build tag; the time_test build tag is required to run those tests. The github CI has intermittent failures on all time related tests; this should reduce those failures and make our CI more reliable.
> client2: gate the time tests with a build tag

- client2/timer_queue.go
action should be run in another routine so that it does not block the TimerQueue worker from waking consitently
> make client2 TimerQueue worker do action in goroutine consistently

- docs/client_integration.md
- **client integration guide: mention hash function used, where to find it, provide golang example**
- **client integration guide: use example service name echo**
- **client integration guide: provide example golang to get events**
- **client integration guide: add golang example with PKIDocument()**
- **client integration guide: add golang reference of ServiceDescriptor**
Here are a few changes. In particular the implementor needs to know how to obtain a node ID hash in order to use the thin client.
I add some more golang example code.
> improve integration guide

- docker/Makefile
- genconfig/main.go
This adds client2's kpclientd as a service to the dockerized testnet infrastucture
> docker, genconfig: add client2 kpclientd to testnet services

- client/timer_queue.go
- client/timer_queue_test.go
- **client/timer_queue: run Push method in goroutine**
- **fix timer_queue_test: do not sleep longer than the replyETA**
fixes deadlock in timer_queue
> fix client timer queue

- client/send.go
- client/session.go
- minclient/connection.go
- **client/send: BlockingSendUnreliableMessageWithContext: do not block on sendWaitChan at Halt**
- **client/session: improve debug logging**
- **client/send: log reason for context.Done**
- **client/session: halt workers before self**
- **client/send: don't delete the reply channel if a response was not received**
- **client/send: do not block writing to abandoned replyWaitChan**
- **client/send: use buffered sentWaitChan, always close sentWaitChan when done**
fixes deadlock in client when worker is unable to write response
> fix client blocking send

- client2/pigeonhole.go
- courier/server/plugin.go
- go.mod
- go.sum
- pigeonhole/geo/geometry.go
- pigeonhole/geo/geometry_test.go
- pigeonhole/message_types_test.go
- pigeonhole/pigeonhole_messages.trunnel
- pigeonhole/trunnel_messages.go
- replica/cryptography_model_tests/client_courier_test.go
- replica/integration_tests/courier_replica_integration_test.go
- vendor/github.com/katzenpost/hpqc/bacap/bacap.go
- vendor/modules.txt
Use latest hpqc with bacap bug fix.
Teach courier to cache all reads and writes.
Update pigeonhole geometry and related tests
to account for not having an IsRead field.
> Use latest hpqc with bacap bug fix
